### ISSUE TITLE
is-leaving does not wait for transition to end

### ISSUE THREAD

**Issue by loup-brun** [gmrchk/swup#35]
Hi,

The element correctly transitions in, but there is no transition out. I am using your regular example (markup and js).

Here's the css I'm using

```css
.a-fade {
  transition: .8s;
  opacity: 1;
}

html.is-animating .a-fade {
  opacity: 0;
}

/* no luck here either*/
html.is-leaving .a-fade {
  opacity: 0;
}
```

I'm using the most recent build of **Swup** (`1.0.2` reads the `package.json`).

Thanks for checking this out!
